# Generated by Django 2.0.3 on 2018-08-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='height_scope',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='position',
            name='width_scope',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='position',
            name='x_position',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='position',
            name='y_position',
            field=models.FloatField(default=0.0),
        ),
    ]
