# Generated by Django 2.0.3 on 2018-09-25 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Positions', '0002_auto_20180829_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('position_id',)},
        ),
        migrations.AddField(
            model_name='position',
            name='timeChange',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
