# Generated by Django 2.0.3 on 2018-10-31 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Positions', '0004_auto_20181009_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='avg_x',
        ),
        migrations.RemoveField(
            model_name='position',
            name='avg_y',
        ),
        migrations.RemoveField(
            model_name='position',
            name='height_scope',
        ),
        migrations.RemoveField(
            model_name='position',
            name='width_scope',
        ),
        migrations.RemoveField(
            model_name='position',
            name='x_position',
        ),
        migrations.RemoveField(
            model_name='position',
            name='y_position',
        ),
    ]
