# Generated by Django 2.0.3 on 2018-09-25 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ('zone_id',)},
        ),
    ]
